version: '3.9'
services:
  web:
    build: .
    # command: python /app/manage.py runserver 0.0.0.0:8000
    command: gunicorn django_project.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env.dev
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web

volumes:
  postgres_data: