version: '3.9'
services: # (or containers)
  web:
    build: . # look in the current directory for our Dockerfile
    ports:
      - '8000:8000' # map port 8000 on the host to port 8000 on the container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # the volumes mount automatically syncs the Docker filesystem with our local computer’s filesystem. if we make a change to the code within Docker it will automatically be synced with the local filesystem.